import { Injectable } from '@nestjs/common';

@Injectable()
export class MenuService {
  private menuItems = [
    {
      itemId: 0,
      restId: 0,
      itemName: 'Butter Chicken',
      itemPrice: 12.99,
      itemDescription:
        'Tender chicken pieces in a rich, creamy tomato-based curry sauce',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 2,
      itemSpiceLevel: 4,
      itemAvailable: true,
      itemBestSeller: true,
      itemIsVeg: false,
      itemIsJain: false,
    },
    {
      itemId: 1,
      restId: 0,
      itemName: 'Paneer Tikka',
      itemPrice: 9.99,
      itemDescription:
        'Grilled cottage cheese cubes marinated in spices and yogurt',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 1,
      itemSpiceLevel: 3,
      itemAvailable: true,
      itemBestSeller: true,
      itemIsVeg: true,
      itemIsJain: false,
    },
    {
      itemId: 2,
      restId: 0,
      itemName: 'Gulab Jamun',
      itemPrice: 5.99,
      itemDescription:
        'Sweet milk-solid balls soaked in rose-flavored sugar syrup',
      itemSweet: true,
      itemSpicy: false,
      itemSweetLevel: 5,
      itemSpiceLevel: 0,
      itemAvailable: true,
      itemBestSeller: false,
      itemIsVeg: true,
      itemIsJain: true,
    },
    {
      itemId: 3,
      restId: 0,
      itemName: 'Veg Biryani',
      itemPrice: 11.99,
      itemDescription:
        'Fragrant basmati rice cooked with mixed vegetables and aromatic spices',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 1,
      itemSpiceLevel: 3,
      itemAvailable: true,
      itemBestSeller: true,
      itemIsVeg: true,
      itemIsJain: false,
    },
    {
      itemId: 4,
      restId: 0,
      itemName: 'Chicken Tikka Masala',
      itemPrice: 13.99,
      itemDescription: 'Grilled chicken in a creamy, spiced tomato-based curry',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 2,
      itemSpiceLevel: 4,
      itemAvailable: true,
      itemBestSeller: true,
      itemIsVeg: false,
      itemIsJain: false,
    },
    {
      itemId: 5,
      restId: 0,
      itemName: 'Jain Thali',
      itemPrice: 14.99,
      itemDescription:
        'Complete meal with rotis, dal, sabzi, rice, and salad (Jain preparation)',
      itemSweet: false,
      itemSpicy: false,
      itemSweetLevel: 1,
      itemSpiceLevel: 1,
      itemAvailable: true,
      itemBestSeller: false,
      itemIsVeg: true,
      itemIsJain: true,
    },
    {
      itemId: 6,
      restId: 0,
      itemName: 'Mango Lassi',
      itemPrice: 4.99,
      itemDescription: 'Sweet yogurt drink with fresh mango pulp',
      itemSweet: true,
      itemSpicy: false,
      itemSweetLevel: 4,
      itemSpiceLevel: 0,
      itemAvailable: true,
      itemBestSeller: false,
      itemIsVeg: true,
      itemIsJain: true,
    },
    {
      itemId: 7,
      restId: 0,
      itemName: 'Chicken Vindaloo',
      itemPrice: 13.99,
      itemDescription: 'Spicy curry dish with chicken, potatoes, and vinegar',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 1,
      itemSpiceLevel: 5,
      itemAvailable: true,
      itemBestSeller: false,
      itemIsVeg: false,
      itemIsJain: false,
    },
    {
      itemId: 8,
      restId: 0,
      itemName: 'Samosa',
      itemPrice: 3.99,
      itemDescription: 'Crispy pastry filled with spiced potatoes and peas',
      itemSweet: false,
      itemSpicy: true,
      itemSweetLevel: 1,
      itemSpiceLevel: 3,
      itemAvailable: true,
      itemBestSeller: true,
      itemIsVeg: true,
      itemIsJain: false,
    },
    {
      itemId: 9,
      restId: 0,
      itemName: 'Kheer',
      itemPrice: 5.99,
      itemDescription:
        'Traditional rice pudding with milk, sugar, and cardamom',
      itemSweet: true,
      itemSpicy: false,
      itemSweetLevel: 4,
      itemSpiceLevel: 0,
      itemAvailable: true,
      itemBestSeller: false,
      itemIsVeg: true,
      itemIsJain: true,
    },
  ];

  public GetAllByRestId(restId: number) {
    return this.menuItems.filter((i) => i.restId == restId);
  }
}
